server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    username: user
    password: password
    url: jdbc:mysql://localhost:3306/fraud
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: "true"
    hibernate:
      ddl-auto: update
    show-sql: "true"
